#!/bin/sh


#!/usr/bin/env ruby
#
# Electron版Serencastに引数を渡す
#

# if !ARGV[0] || !ARGV[1]
#   STDERR.puts "% sc MasuiCast Anime"
#   exit
# end
#
# project = ARGV[0]
# page = ARGV[1]

# if File.exist?("/Users/masui/Serencast/app/docs/mac/Serencast.app/Contents/MacOS/Serencast") then
#   system <<EOF
# export SERENCAST_PROJECT=#{ARGV[0]}
# export SERENCAST_PAGE=#{ARGV[1]}
# open -a /Users/masui/Serencast/app/docs/mac/Serencast.app/Contents/MacOS/Serencast
# EOF
# else
#   system "SERENCAST_PROJECT=#{ARGV[0]} SERENCAST_PAGE=#{ARGV[1]} electron /Users/masui/Serencast/app"
# end

# system "/Users/masui/Serencast/app/docs/mac/Serencast.app/Contents/MacOS/Serencast . #{ARGV[0]} #{ARGV[1]}"

# echo $1 $2
/Users/masui/Serencast/app/docs/mac/Serencast.app/Contents/MacOS/Serencast . $1 $2
