#!/usr/bin/env ruby
#
# Electron版Serencastに引数を渡す
#

if !ARGV[0] || !ARGV[1]
  STDERR.puts "% sc MasuiCast Anime"
  exit
end

project = ARGV[0]
page = ARGV[1]

if File.exist?("/Users/masui/Serencast/app/docs/mac/Serencast.app/Contents/MacOS/Serencast") then
  system <<EOF
export SERENCAST_PROJECT=#{project}
export SERENCAST_PAGE=#{page}
open -a /Users/masui/Serencast/app/docs/mac/Serencast.app/Contents/MacOS/Serencast
EOF
else
  system "SERENCAST_PROJECT=#{project} SERENCAST_PAGE=#{page} electron /Users/masui/Serencast/app"
end
